### ISSUE TITLE
Google OAuth process

### ISSUE THREAD

**Issue by freeheeling** [Not-Zorro/penpal#1]
```
As a unregistered user
When I visit the login path
Then I should see a link that is styled like a button that says "Sign in with Google"
And when I click on "Connect with Google"
Then I should go through the OAuth process
And I should be redirected to the registration path
And I should see a registration page
```
**Tasks**
- [x] Create User table with columns: first_name, last_name, email, token
- [x] Create view
- [x] Create User model
- [x] Create User controller
